config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  "chat_groups#index"
  resources :chat_groups, only: [:new, :edit, :create, :update] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_group.rb
class ChatGroup < ApplicationRecord
  has_many :group_users
  has_many :messages
  has_many :users, through: :group_users
  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :chat_group
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
  # MessageBroadcastJobを呼び出す
  belongs_to :user
  belongs_to :chat_group
  validates :body, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :group_users
  has_many :chat_groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up ,keys: [:name])
    devise_parameter_sanitizer.permit(:account_update ,keys: [:name])
  end
end

app/controllers/chat_groups_controller.rb
class ChatGroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @chat_groups = current_user.chat_groups
  end

  def new
    @chat_group = ChatGroup.new
  end
  def create
    @chat_group = ChatGroup.new(chat_group_params)
    if @chat_group.save
       redirect_to root_path, notice: 'グループが作成されました。'
    else
       render :new, alert: "失敗"
    end

  end
  def show
  end

  def edit
  end

  def update
    if ChatGroup.update(chat_group_params)
      redirect_to root_path , notice: "チャットグループが編集されました。"
    else
      render :edit, alert: "失敗"
    end
  end

  private
  def chat_group_params
    params.require(:chat_group).permit(:name, {user_ids: []})
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @chat_groups = current_user.chat_groups
    @chat_group = ChatGroup.find(params[:chat_group_id])

    @message = Message.new
    @messages = @chat_group.messages

    # respond_to do |format|
    #   format.html { render :index }
    #   format.json { render json: @chat_group.messages }
    # end
  end

  # def create
  # #   @messages = Message.where(chat_group_id: params[:chat_group_id])
  # #   @message = current_user.messages.new(message_params)
  # #   if @message.save
  # #     respond_to do |format|
  # #       format.html{redirect_to :back}
  # #       format.json{render json: @message}
  # #     end
  # #   else
  # #     redirect_to root_path, notice: "失敗"
  # #   end
  # end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(chat_group_id: params[:chat_group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('name LIKE ?', "%#{params[:name]}%")

    respond_to do |format|
      format.json { render json: @users }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_groups_helper.rb
module ChatGroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_groups/_form.html.haml
= form_for @chat_group do |f|
  - if @chat_group.errors.any?
    .chat-group-form__errors
      %h2= "#{pluralize(@chat_group.errors.count, "error")} prohibited this chat_group from being saved:"
      %ul
        - @chat_group.errors.full_messages.each do |msg|
          %li= msg
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, 'グループ名', class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label 'チャットメンバーを追加', class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{ type: "text", placeholder: '追加したいユーザー名を入力してください' }
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label 'チャットメンバー', class: 'chat-group-form__label'
    .chat-group-form__field--right
      #chat-group-users
        - @chat_group.users.each do |user|
          .chat-group-user.clearfix{ id: "chat-group-user-#{user.id}" }
            %input{ type: "hidden", name: "chat_group[user_ids][]", value: user.id }
            %p.chat-group-user__name= user.name
            - unless user.id == current_user.id
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove{ 'data-user-id': user.id } 削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit 'Save', class: 'chat-group-form__action-btn'

app/views/chat_groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  =render 'form'

app/views/chat_groups/index.html.haml
.chat
  .chat-side
    .chat-user
      %h5=current_user.name
      .chat-user__actions
        / ↓歯車とかのロゴ
        =link_to new_chat_group_path, class: "chat-user__action" do
          =icon('pencil-square-o')
        =link_to edit_user_registration_path, class: "chat-user__action" do
          =icon('cog')
    %ul.chat-groups
      -@chat_groups.each do |chat_group|
        %li.chat-group
          =link_to chat_group_messages_path(chat_group.id), class: "chat-group__link" do
            %p.chat-group__name
              =chat_group.name
            %p.chat-group__massage
  .chat-main

app/views/chat_groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  =render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FreeChat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    -flash.each do |key, value|
      %p{class: key}
        =value
    = yield

app/views/messages/_message.html.haml
%li.chat-message
  .chat-message__header
    %p.chat-message__name=message.user.name
    %p.chat-message__time=message.created_at
  %p.chat-message__body=message.body
  - if message.image?
    %br
    = image_tag(message.image)

app/views/messages/create.js.erb
// $('#message_body').val("");
// $('ul.chat-messages').html("<%= j(render @messages) %>");

app/views/messages/index.html.haml
.chat
  .chat-side
    .chat-user
      %h5=current_user.name
      .chat-user__actions
        / ↓歯車とかのロゴ
        =link_to new_chat_group_path, class: "chat-user__action" do
          =icon('pencil-square-o')
        =link_to edit_user_registration_path, class: "chat-user__action" do
          =icon('cog')
    %ul.chat-groups
      -@chat_groups.each do |chat_group|
        %li.chat-group
          =link_to chat_group_messages_path(chat_group.id), class: "chat-group__link" do
            %p.chat-group__name
              =chat_group.name
            %p.chat-group__massage
  .chat-main
    .chat-header
      .chat-header--left
        %h2=@chat_group.name
        %p.chat-header__users
          -@chat_group.users.each do |user|
            %span.chat-header__user=user.name
      .chat-header--right
        .chat-header__edit-btn=link_to 'edit', edit_chat_group_path(@chat_group)
    .chat-body
      %ul.chat-messages
        =render @messages
    .chat-footer
      = form_for [@chat_group, @message], class: 'js-form clearfix' do |f|
        =f.hidden_field :chat_group, value: "#{@chat_group.id}"
        =f.hidden_field :user_id, value: "#{current_user.id}"
        .chat-footer__body
          = f.text_area :body, row: 1, placeholder: 'type a message'
          %label.chat-footer__file
            = f.file_field :image
            =icon('image')
        = f.submit 'Send', id: "message_botton"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
        = devise_error_messages!
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :password
            %i (変更したくない場合は、空白のままにしておいてください)
          .field-input
            = f.password_field :password, autocomplete: "off"
        .field
          .field-label
            = f.label :password_confirmation
          .field-input
            = f.password_field :password_confirmation, autocomplete: "off"
        .field
          .field-label
            = f.label :current_password
            %i (変更には現在のパスワードの入力が必要です)
          .field-input
            = f.password_field :current_password, autocomplete: "off"
        .actions
          = f.submit "Update", class: 'btn'